### ISSUE TITLE
Fix registration field

### ISSUE THREAD

**Issue by sabanitech** [Sabani-Tech/nasho-learn-be-laravel#11]
- field username and email become to umail

**Comment by sabanitech** [comment]
@syamsulapp task assigned with you

**Comment by xamppsul** [comment]
@chairoel mas saya sudah perbaiki logic registernya yah. Ini untuk APis Contract nya:

{
    "nama_lengkap": string,
    "umail": string,
    "password": string,
    "password_confirmation": string,
}
