### ISSUE TITLE
feature/improve-category-list-materi-by-category

### ISSUE THREAD

**Issue by xamppsul** [Sabani-Tech/nasho-learn-be-laravel#17]
- [category] list materi base on category
- [materi] show category from materi

**Comment by xamppsul** [comment]
@chairoel mas tolong di review dulu yah sampe fix abis itu baru di approve

**Comment by chairoel** [comment]
hanya perlu membarikan response list materi hilangkan permalink

**Comment by chairoel** [comment]
perlu adanya tulisan arab juga menyesuaikan design
