### ISSUE TITLE
[APis_contract] implementation auth user and admin

### ISSUE THREAD

**Issue by xamppsul** [Sabani-Tech/nasho-learn-be-laravel#7]
[goals] 
- auth user
- auth admin
- roles

**Comment by xamppsul** [comment]
https://drive.google.com/file/d/16o5or9ednU470pRr_v5yzHebSiaPe_2u/view?usp=drive_link

@chairoel ini api contract untuk yang auth user dan auth admin nya,insyallah yang lainnya akan menyusul segera

**Comment by chairoel** [comment]
tolong di tambahkan field error di reponse API 

{
    **"error": true,**
    "statusCode": 401,
    "message": "platform not exists"
}


{
    **"error": false,**
    "statusCode": 200,
    "message": "success",
    "data": {}
}

**Comment by xamppsul** [comment]
> tolong di tambahkan field error di reponse API
> 
> { **"error": true,** "statusCode": 401, "message": "platform not exists" }
> 
> { **"error": false,** "statusCode": 200, "message": "success", "data": {} }

@chairoel done yah mas monggo di cek kembali
